#!/bin/bash
echo "=========================================="
echo "GitHub Actions 构建状态检查"
echo "=========================================="
echo ""
echo "请打开以下链接查看构建状态："
echo "https://github.com/Neplen/fangdiuqi/actions"
echo ""
echo "构建触发时间：$(date)"
echo "最新提交：$(git log --oneline -1)"
echo ""
echo "如果构建失败，请："
echo "1. 复制错误信息"
echo "2. 告诉我错误内容"
echo "3. 我会自动修复并重新推送"
echo "=========================================="
